version: '2.1'
services:

    node-steckerbot:
      build:
        context: ./data/Dockerfiles/node
        args:
          - SB_VERSION
      depends_on:
        mariadb-steckerbot:
          condition: service_healthy
      healthcheck:
        test: ["CMD", "nslookup", "google.com", "127.0.0.1"]
        interval: 60s
        timeout: 3s
        retries: 10
      volumes:
        - nodemodules-vol-1:/home/node/steckerbot/node_modules
        - nodeconfig-vol-1:/home/node/steckerbot/settings
      environment:
        - MYSQL_DB_HOST=mariadb-steckerbot
      env_file:
        - ./.env
      ports:
        - "127.0.0.1:${HOST_PORT:-9001}:${EP_PORT:-9001}"
      restart: always
      dns:
        - 172.55.1.254
        - 8.8.8.8
        - 4.4.4.4
      dns_search: steckerbot-network
      networks:
        steckerbot-network:
          ipv4_address: 172.55.1.240
          aliases:
            - node

    mariadb-steckerbot:
      image: mariadb:10.3
      command: mysqld --max_allowed_packet=128M
      healthcheck:
        test: ["CMD", "mysqladmin", "ping", "--host", "localhost", "--silent"]
        interval: 5s
        timeout: 5s
        retries: 10
      volumes:
        - mariadb-vol-1:/var/lib/mysql/
      environment:
        - MYSQL_ROOT_PASSWORD=${DBROOT}
        - MYSQL_DATABASE=${DBNAME}
        - MYSQL_USER=${DBUSER}
        - MYSQL_PASSWORD=${DBPASS}
      restart: always
      dns:
        - 172.55.1.254
        - 8.8.8.8
        - 4.4.4.4
      dns_search: steckerbot-network
      networks:
        steckerbot-network:
          ipv4_address: 172.55.1.250
          aliases:
            - mariadb

networks:
  steckerbot-network:
    driver: bridge
    enable_ipv6: false
    ipam:
      driver: default
      config:
        - subnet: 172.55.1.0/24

volumes:
  mariadb-vol-1:
  nodemodules-vol-1:
  nodeconfig-vol-1:
