version: "3"
services:


  db:
    container_name: db
    image: "mysql"
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--host", "localhost", "--silent"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - ./db-data:/docker-entrypoint-initdb.d/:ro
    networks:
      - dbnet
    ports:
      - "3306:3306"
    env_file:
      - steckerbot.env

  slackbot:
    container_name: slackbot
    build: .
    image: slackbot
    restart: always
    user: "hubot"
    env_file:
        - steckerbot.env
    depends_on:
        - "db"
    networks:
      - dbnet

networks:
  dbnet:

volumes:
  db-data:
