@startuml
!include skin.puml

title Deploymentdiagramm

actor Nutzer
component Slack
interface Internet
frame Appserver {
component Firewall
note right of Firewall : Ports 80 und 443
component Chatbot
interface MySQL
interface iCalFeed
note left of iCalFeed : optional
database Termindatenbank
}

Nutzer <--> Slack 
Slack <--> Internet
Internet <--> Firewall
Firewall <--> Chatbot
Chatbot <--> MySQL
MySQL <-> Termindatenbank

Nutzer <..> iCalFeed
Termindatenbank <..> iCalFeed

@enduml
