@startuml
!include skin.puml
left to right direction

:Mitarbeiter: as MA
MA --> (Termin anlegen)
MA --> (Termin abfragen)
MA --> (Termin zusagen)
MA --> (Termin absagen)

:Administrator: as admin
admin --> (Termin löschen)
admin --> (Nutzer anlegen)
admin --> (Nutzer löschen)
admin --> (Berechtigungen des Nutzers ändern)

admin --|> MA : includes

@enduml
